### PR TITLE
Adds pop operation.

### PR DESCRIPTION
**Pull request by remexre**

### CODE REVIEW

**Review by krame505 — APPROVED** [review]

**Review by ericvanwyk — COMMENTED** [review]
So we have `pop` but no `push`?  That is fine if this is expected or traditional nomenclature for operations on vectors.  Is that the case?

**Comment by remexre** [comment]
The push operator is named `append`, unfortunately... I guess adding an alias would be trivial?

**Comment by krame505** [comment]
That's fine with me.

**Comment by ericvanwyk** [comment]
that might be nice - just be clear that `push` is an alias for `append`.  Thanks.

**Pull request merged**
